module Utility {
  interface ClientCallback {
    wstring startRound();
    void roundEnd();
    void gameFinish();
    unsigned long getScore(in long time);
    unsigned long getRoundTime(in long time);
    unsigned long getQueueTime(in long time);
    unsigned long getGameTime(in long time);
  };

  exception LoginException {
    string reason;
  };

  exception LogoutException {
    string reason;
  };

  exception GameStartException {
      string reason;
    };


  interface ServerUtility {
    void login(in wstring username, in wstring passwd) raises (LoginException);
    void loginCallback(in ClientCallback clientCallback);
    void logout(in ClientCallback clientCallback) raises (LogoutException);
    boolean checkUser(in wstring userNPasswd, in wstring gameID);
    boolean checkWord(in wstring answer, in wstring playerID, in wstring gameID);
    void startGame(in wstring user) raises (GameStartException);
    wstring showWinnerOfRound();
    long showScore(in wstring user, in wstring gameID);
    wstring getLetterChoice(in wstring gameID);
  };
};