package CORBA_IDL.Utility;


/**
* CORBA_IDL.Utility/_PlayerUtilityStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public class _PlayerUtilityStub extends org.omg.CORBA.portable.ObjectImpl implements CORBA_IDL.Utility.PlayerUtility
{

  public void login (String username, String passwd) throws CORBA_IDL.Utility.LoginException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_wstring (username);
                $out.write_wstring (passwd);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CORBA_IDL.Utility/LoginException:1.0"))
                    throw CORBA_IDL.Utility.LoginExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                login (username, passwd        );
            } finally {
                _releaseReply ($in);
            }
  } // login

  public void userCallback (CORBA_IDL.Utility.ClientCallback clientCallback, String username)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("userCallback", true);
                CORBA_IDL.Utility.ClientCallbackHelper.write ($out, clientCallback);
                $out.write_wstring (username);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                userCallback (clientCallback, username        );
            } finally {
                _releaseReply ($in);
            }
  } // userCallback

  public void logout (CORBA_IDL.Utility.ClientCallback clientCallback, String username) throws CORBA_IDL.Utility.LogoutException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("logout", true);
                CORBA_IDL.Utility.ClientCallbackHelper.write ($out, clientCallback);
                $out.write_wstring (username);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CORBA_IDL.Utility/LogoutException:1.0"))
                    throw CORBA_IDL.Utility.LogoutExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                logout (clientCallback, username        );
            } finally {
                _releaseReply ($in);
            }
  } // logout

  public String startGame (String user) throws CORBA_IDL.Utility.GameStartException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGame", true);
                $out.write_wstring (user);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CORBA_IDL.Utility/GameStartException:1.0"))
                    throw CORBA_IDL.Utility.GameStartExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startGame (user        );
            } finally {
                _releaseReply ($in);
            }
  } // startGame

  public void checkWord (String answer, String playerID, String gameID) throws CORBA_IDL.Utility.InvalidWordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("checkWord", true);
                $out.write_wstring (answer);
                $out.write_wstring (playerID);
                $out.write_wstring (gameID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CORBA_IDL.Utility/InvalidWordException:1.0"))
                    throw CORBA_IDL.Utility.InvalidWordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                checkWord (answer, playerID, gameID        );
            } finally {
                _releaseReply ($in);
            }
  } // checkWord

  public int showScore (String user, String gameID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("showScore", true);
                $out.write_wstring (user);
                $out.write_wstring (gameID);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return showScore (user, gameID        );
            } finally {
                _releaseReply ($in);
            }
  } // showScore

  public void getQueueTime (String username)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getQueueTime", true);
                $out.write_wstring (username);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getQueueTime (username        );
            } finally {
                _releaseReply ($in);
            }
  } // getQueueTime

  public void getRoundTime (String username, String gameID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRoundTime", true);
                $out.write_wstring (username);
                $out.write_wstring (gameID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getRoundTime (username, gameID        );
            } finally {
                _releaseReply ($in);
            }
  } // getRoundTime

  public String getLetterChoice (String gameID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLetterChoice", true);
                $out.write_wstring (gameID);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLetterChoice (gameID        );
            } finally {
                _releaseReply ($in);
            }
  } // getLetterChoice

  public String getGameID (String username)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGameID", true);
                $out.write_wstring (username);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGameID (username        );
            } finally {
                _releaseReply ($in);
            }
  } // getGameID

  public String getRoundCount (String gameID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRoundCount", true);
                $out.write_wstring (gameID);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRoundCount (gameID        );
            } finally {
                _releaseReply ($in);
            }
  } // getRoundCount

  public String[] getLeaderboardUsernames ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboardUsernames", true);
                $in = _invoke ($out);
                String $result[] = CORBA_IDL.Utility.playerLeaderboardHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboardUsernames (        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboardUsernames

  public int[] getLeaderboardPoints ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboardPoints", true);
                $in = _invoke ($out);
                int $result[] = CORBA_IDL.Utility.playerLeaderboardPointsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboardPoints (        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboardPoints

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBA_IDL.Utility/PlayerUtility:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PlayerUtilityStub
