package CORBA_IDL.Utility;


/**
* Utility/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Tuesday, May 21, 2024 9:07:47 AM CST
*/

public interface ClientCallbackOperations 
{
  String startRound ();
  void roundEnd (String roundWinner, int points);
  void gameFinish (String gameWinner, String points);
  int getScore (int time);
  void getRoundTime (int time);
  void getQueueTime (int time);
  void getLetterChoice (String letters);
  void getChampion (String username, String points);
} // interface ClientCallbackOperations
