package CORBA_IDL.Utility;


/**
* CORBA_IDL.Utility/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public interface ClientCallbackOperations 
{
  String startRound ();
  void roundEnd (String roundWinner, int points);
  void gameFinish (String gameWinner, String points);
  int getScore (int time);
  void getRoundTime (int time);
  void getQueueTime (int time);
  void getLetterChoice (String letters);
  void getChampion (String username, String points);
} // interface ClientCallbackOperations
