package CORBA_IDL.Utility;


/**
* Utility/ClientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Tuesday, May 21, 2024 9:07:47 AM CST
*/

public interface ClientCallback extends ClientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientCallback
