package CORBA_IDL.Utility;


/**
* CORBA_IDL.Utility/GameStartException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public final class GameStartException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GameStartException ()
  {
    super(GameStartExceptionHelper.id());
  } // ctor

  public GameStartException (String _reason)
  {
    super(GameStartExceptionHelper.id());
    reason = _reason;
  } // ctor


  public GameStartException (String $reason, String _reason)
  {
    super(GameStartExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GameStartException
