package CORBA_IDL.Utility;

/**
* Utility/GameStartExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 23, 2024 1:26:12 AM CST
*/

public final class GameStartExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameStartException value = null;

  public GameStartExceptionHolder ()
  {
  }

  public GameStartExceptionHolder (GameStartException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameStartExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameStartExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameStartExceptionHelper.type ();
  }

}
