package CORBA_IDL.Utility;

/**
* Utility/LoginExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Tuesday, May 21, 2024 9:07:47 AM CST
*/

public final class LoginExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginException value = null;

  public LoginExceptionHolder ()
  {
  }

  public LoginExceptionHolder (LoginException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginExceptionHelper.type ();
  }

}
