package CORBA_IDL.Utility;


/**
* CORBA_IDL.Utility/LoginException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public final class LoginException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public LoginException ()
  {
    super(LoginExceptionHelper.id());
  } // ctor

  public LoginException (String _reason)
  {
    super(LoginExceptionHelper.id());
    reason = _reason;
  } // ctor


  public LoginException (String $reason, String _reason)
  {
    super(LoginExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class LoginException
