package CORBA_IDL.Utility;

/**
* Utility/LogoutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Monday, May 20, 2024 10:38:18 PM CST
*/

public final class LogoutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public LogoutException value = null;

  public LogoutExceptionHolder ()
  {
  }

  public LogoutExceptionHolder (LogoutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LogoutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LogoutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LogoutExceptionHelper.type ();
  }

}
