package CORBA_IDL.Utility;


/**
* Utility/PlayerUtilityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Utility.idl
* Wednesday, May 22, 2024 11:19:37 AM SGT
*/

public interface PlayerUtilityOperations 
{
  void login (String username, String passwd) throws LoginException;
  void userCallback (ClientCallback clientCallback, String username);
  void logout (ClientCallback clientCallback, String username) throws LogoutException;
  String startGame (String user) throws GameStartException;
  void checkWord (String answer, String playerID, String gameID) throws InvalidWordException;
  int showScore (String user, String gameID);
  void getQueueTime (String username);
  void getRoundTime (String username, String gameID);
  String getLetterChoice (String gameID);
  String getGameID (String username) throws GameStartException;
  String getRoundCount (String gameID);
  String[] getLeaderboardUsernames ();
  int[] getLeaderboardPoints ();
  int getWinsCount (String username, String gameId);
  void leaveGame (String gameID, String username);
} // interface PlayerUtilityOperations asd
