package CORBA_IDL.Utility;


/**
* Utility/PlayerUtility.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Monday, May 20, 2024 10:38:18 PM CST
*/

public interface PlayerUtility extends PlayerUtilityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerUtility
