package CORBA_IDL.Utility;


/**
* CORBA_IDL.Utility/PlayerUtilityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public interface PlayerUtilityOperations 
{
  void login (String username, String passwd) throws CORBA_IDL.Utility.LoginException;
  void userCallback (CORBA_IDL.Utility.ClientCallback clientCallback, String username);
  void logout (CORBA_IDL.Utility.ClientCallback clientCallback, String username) throws CORBA_IDL.Utility.LogoutException;
  String startGame (String user) throws CORBA_IDL.Utility.GameStartException;
  void checkWord (String answer, String playerID, String gameID) throws CORBA_IDL.Utility.InvalidWordException;
  int showScore (String user, String gameID);
  void getQueueTime (String username);
  void getRoundTime (String username, String gameID);
  String getLetterChoice (String gameID);
  String getGameID (String username);
  String getRoundCount (String gameID);
  String[] getLeaderboardUsernames ();
  int[] getLeaderboardPoints ();
} // interface PlayerUtilityOperations
