package CORBA_IDL.Utility;


/**
* Utility/PlayerUtility.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Tuesday, May 21, 2024 9:07:47 AM CST
*/

public interface PlayerUtility extends PlayerUtilityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerUtility
