package CORBA_IDL.Utility;

/**
* Utility/PlayerUtilityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 23, 2024 12:56:59 AM CST
*/

public final class PlayerUtilityHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerUtility value = null;

  public PlayerUtilityHolder ()
  {
  }

  public PlayerUtilityHolder (PlayerUtility initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerUtilityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerUtilityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerUtilityHelper.type ();
  }

}
