package CORBA_IDL.Utility;

/**
* CORBA_IDL.Utility/PlayerUtilityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public final class PlayerUtilityHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA_IDL.Utility.PlayerUtility value = null;

  public PlayerUtilityHolder ()
  {
  }

  public PlayerUtilityHolder (CORBA_IDL.Utility.PlayerUtility initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA_IDL.Utility.PlayerUtilityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA_IDL.Utility.PlayerUtilityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA_IDL.Utility.PlayerUtilityHelper.type ();
  }

}
