package CORBA_IDL.Utility;


/**
* CORBA_IDL.Utility/PlayerUtilityHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

abstract public class PlayerUtilityHelper
{
  private static String  _id = "IDL:CORBA_IDL.Utility/PlayerUtility:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBA_IDL.Utility.PlayerUtility that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBA_IDL.Utility.PlayerUtility extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CORBA_IDL.Utility.PlayerUtilityHelper.id (), "PlayerUtility");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBA_IDL.Utility.PlayerUtility read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PlayerUtilityStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBA_IDL.Utility.PlayerUtility value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CORBA_IDL.Utility.PlayerUtility narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBA_IDL.Utility.PlayerUtility)
      return (CORBA_IDL.Utility.PlayerUtility)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CORBA_IDL.Utility._PlayerUtilityStub stub = new CORBA_IDL.Utility._PlayerUtilityStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CORBA_IDL.Utility.PlayerUtility unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBA_IDL.Utility.PlayerUtility)
      return (CORBA_IDL.Utility.PlayerUtility)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CORBA_IDL.Utility._PlayerUtilityStub stub = new CORBA_IDL.Utility._PlayerUtilityStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
