package CORBA_IDL.Utility;


/**
* CORBA_IDL.Utility/playerLeaderboardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public final class playerLeaderboardHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public playerLeaderboardHolder ()
  {
  }

  public playerLeaderboardHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA_IDL.Utility.playerLeaderboardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA_IDL.Utility.playerLeaderboardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA_IDL.Utility.playerLeaderboardHelper.type ();
  }

}
