package Utility;


/**
* Utility/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Friday, May 10, 2024 12:17:25 PM CST
*/

public interface ClientCallbackOperations 
{
  String startRound ();
  void roundEnd (String roundWinner, int points);
  void gameFinish (String gameWinner, String points);
  int getScore (int time);
  void getRoundTime (int time);
  void getQueueTime (int time);
  void getLetterChoice (String letters);
} // interface ClientCallbackOperations
