package Utility;


/**
* Utility/ClientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Friday, May 10, 2024 12:17:25 PM CST
*/

public interface ClientCallback extends ClientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientCallback
