package Utility;


/**
* Utility/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 2, 2024 12:31:50 PM CST
*/

public interface ClientCallbackOperations 
{
  String startRound ();
  void roundEnd ();
  void gameFinish ();
} // interface ClientCallbackOperations
