package Utility;


/**
* Utility/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 9, 2024 12:22:12 PM CST
*/

public interface ClientCallbackOperations 
{
  String startRound ();
  void roundEnd ();
  void gameFinish ();
  int getScore (int time);
  void getRoundTime (int time);
  void getQueueTime (int time);
  void getGameTime (int time);
  String getLetterChoice (String letters);
} // interface ClientCallbackOperations
