package Utility;


/**
* Utility/GameStartException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Sunday, May 5, 2024 6:17:25 PM CST
*/

public final class GameStartException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GameStartException ()
  {
    super(GameStartExceptionHelper.id());
  } // ctor

  public GameStartException (String _reason)
  {
    super(GameStartExceptionHelper.id());
    reason = _reason;
  } // ctor


  public GameStartException (String $reason, String _reason)
  {
    super(GameStartExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GameStartException
