package Utility;

/**
* Utility/LogoutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 9, 2024 12:55:53 PM CST
*/

public final class LogoutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Utility.LogoutException value = null;

  public LogoutExceptionHolder ()
  {
  }

  public LogoutExceptionHolder (Utility.LogoutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Utility.LogoutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Utility.LogoutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Utility.LogoutExceptionHelper.type ();
  }

}
