package Utility;


/**
* Utility/PlayerUtilityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 9, 2024 12:55:53 PM CST
*/

public interface PlayerUtilityOperations 
{
  void login (String username, String passwd) throws Utility.LoginException;
  void userCallback (Utility.ClientCallback clientCallback, String username);
  void logout (Utility.ClientCallback clientCallback, String username) throws Utility.LogoutException;

  // boolean checkUser(in wstring userNPasswd, in wstring gameID);
  void checkWord (String answer, String playerID, String gameID) throws Utility.InvalidWordException;
  String startGame (String user) throws Utility.GameStartException;

  // wstring showWinnerOfRound();
  int showScore (String user, String gameID);
} // interface PlayerUtilityOperations
