package Utility;


/**
* Utility/PlayerUtilityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Friday, May 10, 2024 12:17:25 PM CST
*/

public interface PlayerUtilityOperations 
{
  void login (String username, String passwd) throws Utility.LoginException;
  void userCallback (Utility.ClientCallback clientCallback, String username);
  void logout (Utility.ClientCallback clientCallback, String username) throws Utility.LogoutException;
  String startGame (String user) throws Utility.GameStartException;
  void checkWord (String answer, String playerID, String gameID) throws Utility.InvalidWordException;
  int showScore (String user, String gameID);
  void getQueueTime (String username);
  void getRoundTime (String username, String gameID);
  String getLetterChoice (String gameID);
  String getGameID (String username);
} // interface PlayerUtilityOperations
