package Utility;


/**
* Utility/playerLeaderboardPointsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Wednesday, May 15, 2024 3:24:14 PM CST
*/

public final class playerLeaderboardPointsHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public playerLeaderboardPointsHolder ()
  {
  }

  public playerLeaderboardPointsHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Utility.playerLeaderboardPointsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Utility.playerLeaderboardPointsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Utility.playerLeaderboardPointsHelper.type ();
  }

}
