package Utility;


/**
* Utility/PlayerUtility.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 16, 2024 5:56:17 PM CST
*/

public interface PlayerUtility extends PlayerUtilityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerUtility
