package Utility;


/**
* Utility/ServerUtilityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Monday, May 6, 2024 1:08:13 PM CST
*/

public interface ServerUtilityOperations 
{
  void login (String username, String passwd) throws Utility.LoginException;
  void loginCallback (Utility.ClientCallback clientCallback);
  void logout (Utility.ClientCallback clientCallback) throws Utility.LogoutException;
  boolean checkUser (String userNPasswd, String gameID);
  boolean checkWord (String answer, String playerID, String gameID);
  void startGame (String user) throws Utility.GameStartException;
  String showWinnerOfRound ();
  int showScore (String user, String gameID);
  String getLetterChoice (String gameID);
} // interface ServerUtilityOperations
