package Utility;


/**
* Utility/ServerUtility.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Sunday, May 5, 2024 8:14:30 PM CST
*/

public interface ServerUtility extends ServerUtilityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerUtility
