package Utility;


/**
* Utility/ServerUtility.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Monday, May 6, 2024 1:08:13 PM CST
*/

public interface ServerUtility extends ServerUtilityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerUtility
