package Utility;


/**
* Utility/ServerUtilityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Thursday, May 2, 2024 12:31:50 PM CST
*/

public interface ServerUtilityOperations 
{
  boolean login (String credentials);
  void loginCallback (Utility.ClientCallback clientCallback);
  void logout (Utility.ClientCallback clientCallback);
  boolean checkUser (String userNPasswd, String gameID);
  boolean checkWord (String answer, String gameID);
  void startGame (String user);
  String showWinnerOfRound ();
  int showScore (String user, String gameID);
  String getLetterChoice (String gameID);
} // interface ServerUtilityOperations
