package Utility;


/**
* Utility/ServerUtility.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Utility.idl
* Wednesday, May 8, 2024 8:39:04 PM CST
*/

public interface ServerUtility extends ServerUtilityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerUtility
