module Utility{

interface serverUtility{
    boolean checkUser(wstring userNPasswd)
    boolean checkWord(wstring answer)
    void start(wstring user)
    wstring showWinner()
    long showScore(wstring user)
    wstring getLetterChoice()

}


}
