module Utility{

interface serverUtility{
    boolean checkUser(wstring userNPasswd)
    boolean checkWord(wstring answer)
    void startGame(wstring user)
    wstring showWinnerOfRound()
    long showScore(wstring user)
    wstring getLetterChoice()
    void joinGame(wstring user)
}

interface ClientCallback{
    void startRound()
    void roundEnd()
    void gameFinish()
}



}
